### ISSUE TITLE
ga.run()

### ISSUE THREAD

**Issue by langongjin** [olmallet81/GALGO#9]
hi, 
```cpp
// running genetic algorithm
ga.run();
```
here `ga.run()` run the iterations inside until the termination. But I want to take the iteration out of `ga.run()`. That means `ga.run()` only feedback the populations, fitnesses, and best for a generation. For instance, I would like the code like
```
for (int generation = 0; generation < maxGenerations; generation++)
{
    ga.run(); //feedback the populations, fitnesses, and best for a generation
}
```
How can I do this?
Thanks!

**Comment by seaseestr** [comment]
It's inside the run function:
   // starting population evolution
   for (nogen = 1; nogen <= nbgen; ++nogen) {
      // evolving population
      pop.evolution();
      // getting best current result
      bestResult = pop(0)->getTotal();
      // outputting results
      if (output) print();
      // checking convergence
      if (tolerance != 0.0) {
         if (fabs(bestResult - prevBestResult) < fabs(tolerance)) {
            break;
         }
         prevBestResult = bestResult;
      }
   }

**Comment by langongjin** [comment]
Thanks for the answer. I actually did it as you said months ago. Leave the idea to the next one who needs it.
